logmane/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('logmaneapp.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
    path('accounts/', include('accounts.urls')),
]

logmaneapp/urls.py
from django.urls import path

from . import views

app_name = 'logmaneapp'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('athlete/', views.AthleteListView.as_view(), name='athlete_list'),
    path('athlete/<int:pk>/', views.AthleteDetailView.as_view(), name='athlete_detail'),
    path('athlete/create/', views.athlete_form, name='athlete_create'),
    path('athlete/records/', views.athlete_records_form, name='athlete_records'),
    path('athlete/<int:pk>/delete/', views.AthleteDelete.as_view(), name='athlete_delete'),
    path('athlete/<int:pk>/update/', views.AthleteUpdate.as_view(), name='athlete_update'),
    path('athlete/records/<int:pk>/delete/', views.AthleteRecordsDelete.as_view(), name='athlete_records_delete'),
    path('athlete/records/<int:pk>/update/', views.AthleteRecordsUpdate.as_view(), name='athlete_records_update'),
    path('event/create/', views.event_form, name='event_create'),
    path('event/<int:pk>/delete/', views.EventDelete.as_view(), name='event_delete'),
    path('event/<int:pk>/update/', views.EventUpdate.as_view(), name='event_update'),
    path('event/', views.EventListView.as_view(), name='event_list'),
    path('event/records/', views.EventRecordsListView.as_view(), name='event_records_list'),
    path('event/records/create/', views.event_records_form, name='event_records_create'),
    path('event/records/<int:pk>/delete/', views.EventRecordsDelete.as_view(), name='event_records_delete'),
    path('event/records/<int:pk>/update/', views.EventRecordsUpdate.as_view(), name='event_records_update'),
]

logmaneapp/models.py
from django.db import models

class Athlete(models.Model):
    class Meta:
        db_table = 'athlete'

    athlete_id = models.AutoField(primary_key=True, unique=True)
    name = models.CharField(max_length=100, verbose_name='選手名')
    gender = models.CharField(max_length=10, verbose_name='性別')
    grade = models.CharField(max_length=10, verbose_name='学年')
    group = models.CharField(max_length=10, verbose_name='パート', null=True)

    def __str__(self):
        return self.name


class Discipline(models.Model):
    class Meta:
        db_table = 'discipline'

    discipline_id = models.AutoField(primary_key=True, unique=True)
    discipline = models.CharField(max_length=100, verbose_name='種目')

    def __str__(self):
        return self.discipline


class Athlete_records(models.Model):

    athlete_id = models.ForeignKey(Athlete, on_delete=models.CASCADE)
    discipline = models.ForeignKey(Discipline, on_delete=models.PROTECT)
    personal_best = models.DecimalField(verbose_name='自己ベスト', max_digits=10, decimal_places=2)
    university_best = models.DecimalField(verbose_name='大学ベスト', max_digits=10, decimal_places=2)
    valid_record = models.DecimalField(verbose_name='有効記録', max_digits=10, decimal_places=2)
    athlete_records_id = models.AutoField(primary_key=True, unique=True)

    class Meta:
        db_table = 'athlete_records'
        constraints = [
            models.UniqueConstraint(fields=['athlete_id', 'discipline'], name='athlete_records_unique')
        ]

    def __str__(self):
        return str(self.athlete_records_id)


class Event(models.Model):
    class Meta:
        db_table = 'event'

    event_id = models.AutoField(primary_key=True, unique=True)
    event = models.CharField(max_length=100, verbose_name='大会名')
    date = models.DateField(verbose_name='日付')

    def __str__(self):
        return self.event


class Stage(models.Model):
    class Meta:
        db_table = 'stage'

    stage_id = models.AutoField(primary_key=True, unique=True)
    stage = models.CharField(max_length=100, verbose_name='ラウンド')

    def __str__(self):
        return self.stage


class Division(models.Model):
    class Meta:
        db_table = 'division'

    division_id = models.AutoField(primary_key=True, unique=True)
    division = models.CharField(max_length=100, verbose_name='区分')

    def __str__(self):
        return self.division


class Event_records(models.Model):


    athlete_id = models.ForeignKey(Athlete, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.PROTECT)
    discipline = models.ForeignKey(Discipline, on_delete=models.PROTECT)
    stage = models.ForeignKey(Stage, on_delete=models.PROTECT)
    record = models.DecimalField(verbose_name='記録', max_digits=10, decimal_places=2)
    wind = models.DecimalField(verbose_name='風速', max_digits=2, decimal_places=1)
    heat = models.CharField(max_length=10, verbose_name='組')
    place = models.CharField(max_length=100, verbose_name='順位')
    division = models.ForeignKey(Division, on_delete=models.PROTECT)
    event_records_id = models.AutoField(primary_key=True, unique=True)

    class Meta:
        db_table = 'event_records'
        constraints = [
            models.UniqueConstraint(fields=['athlete_id', 'event', 'discipline', 'stage'], name='event_records_unique')
        ]

    def __str__(self):
        return str(self.athlete_id.athlete_id)

logmaneapp/forms.py
from django import forms
from .models import Athlete, Discipline, Athlete_records, Event, Event_records, Stage, Division

class AthleteForm(forms.ModelForm):

    class Meta:
        model = Athlete
        fields = ('name', 'gender', 'grade', 'group')
        labels = {
            'name': '選手名',
            'gender': '性別',
            'grade': '学年',
            'group': 'パート'
        }

class AthleteRecordsForm(forms.ModelForm):

    athlete_id = forms.ModelChoiceField(queryset=Athlete.objects.all(), empty_label='選手名')
    discipline = forms.ModelChoiceField(queryset=Discipline.objects.all(), empty_label='種目')
    class Meta:
        model = Athlete_records
        fields = ('athlete_id','discipline', 'personal_best', 'university_best', 'valid_record')
        labels = {
                'personal_best': '自己ベスト',
                'university_best': '大学ベスト',
                'valid_record': '有効記録'
            }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['athlete_id'].queryset = Athlete.objects.all()
        self.fields['athlete_id'].empty_label = '選手名'
        self.fields['discipline'].queryset = Discipline.objects.all()
        self.fields['discipline'].empty_label = '種目'

class EventForm(forms.ModelForm):

        class Meta:
            model = Event
            fields = ('event', 'date')
            labels = {
                'event': '大会名',
                'date': '日付'
            }

class EventRecordsForm(forms.ModelForm):

        athlete_id = forms.ModelChoiceField(queryset=Athlete.objects.all(), empty_label='選手名')
        event = forms.ModelChoiceField(queryset=Event.objects.all(), empty_label='大会名')
        division = forms.ModelChoiceField(queryset=Division.objects.all(), empty_label='区分')
        discipline = forms.ModelChoiceField(queryset=Discipline.objects.all(), empty_label='種目')
        stage = forms.ModelChoiceField(queryset=Stage.objects.all(), empty_label='ステージ')
        class Meta:
            model = Event_records
            fields = ('athlete_id', 'event', 'division', 'discipline', 'stage', 'heat', 'place', 'record','wind')
            labels = {
                    'record': '記録',
                    'heat': '組',
                    'place': '順位',
                    'wind': '風速',
                }

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields['athlete_id'].queryset = Athlete.objects.all()
            self.fields['athlete_id'].empty_label = '選手名'
            self.fields['discipline'].queryset = Discipline.objects.all()
            self.fields['discipline'].empty_label = '種目'
            self.fields['event'].queryset = Event.objects.all()
            self.fields['event'].empty_label = '大会名'
            self.fields['stage'].queryset = Stage.objects.all()
            self.fields['stage'].empty_label = 'ラウンド'
            self.fields['division'].queryset = Division.objects.all()
            self.fields['division'].empty_label = '区分'

logmaneapp/views.py
from typing import Any
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView, FormView
from .models import Athlete, Discipline, Athlete_records, Event, Event_records
from .forms import AthleteForm, AthleteRecordsForm, EventForm, EventRecordsForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required


class IndexView(LoginRequiredMixin, TemplateView):
    template_name = 'index.html'

class AthleteListView(LoginRequiredMixin, ListView):
    template_name = 'athlete_list.html'
    model = Athlete

class AthleteDetailView(LoginRequiredMixin, DetailView):
    template_name = 'athlete_detail.html'
    model = Athlete

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['athlete_records'] = Athlete_records.objects.filter(athlete_id=self.kwargs['pk'])
        context['event_records'] = Event_records.objects.filter(athlete_id=self.kwargs['pk'])
        return context

    athlete = Athlete.objects.all()

@login_required
def athlete_form(request):
    if request.method == 'POST':
        form = AthleteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('logmaneapp:athlete_list')
    else:
        form = AthleteForm()
    context = {'form': form}
    return render(request, 'athlete_create.html', context)

@login_required
def athlete_records_form(request):
    if request.method == 'POST':
        form = AthleteRecordsForm(request.POST)
        if form.is_valid():
            athlete_record = form.save(commit=False)
            athlete_record.save()
            return redirect('logmaneapp:athlete_list')
    else:
        form = AthleteRecordsForm()
    context = {'form': form}
    return render(request, 'athlete_records_form.html', context)

class AthleteDelete(LoginRequiredMixin, DeleteView):
    template_name = 'athlete_delete.html'
    model = Athlete
    success_url = '/athlete/'

class AthleteUpdate(LoginRequiredMixin, UpdateView):
    template_name = 'athlete_update.html'
    model = Athlete
    fields = (['name', 'grade', 'gender', 'group'])
    success_url = '/athlete/'

class AthleteRecordsDelete(LoginRequiredMixin, DeleteView):
    template_name = 'athlete_records_delete.html'
    model = Athlete_records
    success_url = '/athlete/'

class AthleteRecordsUpdate(LoginRequiredMixin, UpdateView):
    template_name = 'athlete_records_update.html'
    model = Athlete_records
    fields = (['personal_best', 'university_best', 'valid_record'])
    success_url = '/athlete/'

@login_required
def event_form(request):
    if request.method == 'POST':
        form = EventForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('logmaneapp:event_list')
    else:
        form = EventForm()
    context = {'form': form}
    return render(request, 'event_create.html', context)

class EventDelete(LoginRequiredMixin, DeleteView):
    template_name = 'event_delete.html'
    model = Event
    success_url = '/athlete/'

class EventUpdate(LoginRequiredMixin, UpdateView):
    template_name = 'event_update.html'
    model = Event
    fields = (['event', 'date'])
    success_url = '/athlete/'

class EventListView(LoginRequiredMixin, ListView):
    template_name = 'event_list.html'
    model = Event

class EventRecordsListView(LoginRequiredMixin, ListView):
    template_name = 'event_records_list.html'
    model = Event_records

@login_required
def event_records_form(request):
    if request.method == 'POST':
        form = EventRecordsForm(request.POST)
        if form.is_valid():
            event_record = form.save(commit=False)
            event_record.save()
            return redirect('logmaneapp:athlete_list')
    else:
        form = EventRecordsForm()
    context = {'form': form}
    return render(request, 'event_records_form.html', context)

class EventRecordsDelete(LoginRequiredMixin, DeleteView):
    template_name = 'event_records_delete.html'
    model = Event_records
    success_url = '/athlete/'

class EventRecordsUpdate(LoginRequiredMixin, UpdateView):
    template_name = 'event_records_update.html'
    model = Event_records
    fields = (['event', 'division', 'discipline', 'stage', 'record', 'heat', 'place', 'wind'])
    success_url = '/athlete/'

logmaneapp/templates/athlete_create.html
{% extends 'base.html' %}

{% block title %}選手登録{% endblock title %}

{% block content %}
<div class="max-w-[85rem] px-4 py-10 sm:px-6 lg:px-8 lg:py-14 mx-auto">
    <div class="max-w-xl mx-auto">
      <div class="text-center">
        <h1 class="text-3xl font-bold text-gray-800 sm:text-4xl dark:text-white">
          選手登録
        </h1>
        <p class="mt-1 text-gray-600 dark:text-gray-400">
            以下のフォームに登録する選手の情報を入力してください。
        </p>
      </div>

      <div class="mt-12">
        <!-- Form -->
        <form method="POST">
          {% csrf_token %}
          <div class="grid gap-4 lg:gap-6">
            <!-- Grid -->
            <div class="grid grid-cols-1 sm:grid-cols-2 gap-4 lg:gap-6">
              <div>
                <label for="{{ form.name.id_for_label }}" class="block text-sm text-gray-700 font-medium dark:text-white">選手名</label>
                <input type="text" name="name" id="name" class="py-3 px-4 block w-full border-gray-200 rounded-md text-sm focus:border-blue-500 focus:ring-blue-500 dark:bg-slate-900 dark:border-gray-700 dark:text-gray-400">
              </div>

              <div>
                <label for="{{ form.grade.id_for_label }}" class="block text-sm text-gray-700 font-medium dark:text-white">学年</label>
                <input type="text" name="grade" id="grade" class="py-3 px-4 block w-full border-gray-200 rounded-md text-sm focus:border-blue-500 focus:ring-blue-500 dark:bg-slate-900 dark:border-gray-700 dark:text-gray-400">
              </div>
            </div>
            <!-- End Grid -->

            <!-- Grid -->
            <div class="grid grid-cols-1 sm:grid-cols-2 gap-4 lg:gap-6">
              <div>
                <label for="{{ form.gender.id_for_label }}" class="block text-sm text-gray-700 font-medium dark:text-white">性別</label>
                <input type="text" name="gender" id="gender" class="py-3 px-4 block w-full border-gray-200 rounded-md text-sm focus:border-blue-500 focus:ring-blue-500 dark:bg-slate-900 dark:border-gray-700 dark:text-gray-400">
              </div>

              <div>
                <label for="{{ form.group.id_for_label }}" class="block text-sm text-gray-700 font-medium dark:text-white">パート</label>
                <input type="text" name="group" id="group" class="py-3 px-4 block w-full border-gray-200 rounded-md text-sm focus:border-blue-500 focus:ring-blue-500 dark:bg-slate-900 dark:border-gray-700 dark:text-gray-400">
              </div>
            </div>
            <!-- End Grid -->
          <div class="mt-6 grid">
            <button type="submit" class="inline-flex justify-center items-center gap-x-3 text-center bg-blue-600 hover:bg-blue-700 border border-transparent text-sm lg:text-base text-white font-medium rounded-md focus:outline-none focus:ring-2 focus:ring-blue-600 focus:ring-offset-2 focus:ring-offset-white transition py-3 px-4 dark:focus:ring-offset-gray-800">保存</button>
          </div>
        </form>
        <!-- End Form -->
      </div>
    </div>
  </div>
{% endblock content %}

logmaneapp/templates/event_list.html
{% extends 'base.html' %}

{% block title %}大会一覧{% endblock title %}

{% block content %}
<!-- Table Section -->
<div class="max-w-[85rem] px-4 py-10 sm:px-6 lg:px-8 lg:py-14 mx-auto">
    <!-- Card -->
    <div class="flex flex-col">
      <div class="-m-1.5 overflow-x-auto">
        <div class="p-1.5 min-w-full inline-block align-middle">
          <div
            class="bg-white border border-gray-200 rounded-xl shadow-sm overflow-hidden dark:bg-slate-900 dark:border-gray-700"
          >

            <div
              class="px-6 py-4 grid gap-3 md:flex md:justify-between md:items-center border-b border-gray-200 dark:border-gray-700"
            >
              <div>
                <h2
                  class="text-xl font-semibold text-gray-800 dark:text-gray-200"
                >
                  大会一覧
                </h2>
              </div>

              <div>
                <div class="inline-flex gap-x-2">
                  <a
                    class="py-2 px-3 inline-flex justify-center items-center gap-2 rounded-md border border-transparent font-semibold bg-blue-500 text-white hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 transition-all text-sm dark:focus:ring-offset-gray-800"
                    href="{% url "logmaneapp:event_create" %}"
                  >
                    <svg
                      class="w-3 h-3"
                      xmlns="http://www.w3.org/2000/svg"
                      width="16"
                      height="16"
                      viewBox="0 0 16 16"
                      fill="none"
                    >
                      <path
                        d="M2.63452 7.50001L13.6345 7.5M8.13452 13V2"
                        stroke="currentColor"
                        stroke-width="2"
                        stroke-linecap="round"
                      />
                    </svg>
                    大会を追加
                  </a>
                </div>
              </div>
            </div>


            <!-- Table -->
            <table
              class="min-w-full divide-y divide-gray-200 dark:divide-gray-700"
            >
              <thead class="bg-gray-50 dark:bg-slate-800">
                <tr>
                  <th scope="col" class="px-6 py-3 text-left">
                    <div class="flex items-center gap-x-2">
                      <span
                        class="text-xs font-semibold uppercase tracking-wide text-gray-800 dark:text-gray-200"
                      >
                        大会名
                      </span>
                    </div>
                  </th>

                  <th scope="col" class="px-6 py-3 text-left">
                    <div class="flex items-center gap-x-2">
                      <span
                        class="text-xs font-semibold uppercase tracking-wide text-gray-800 dark:text-gray-200"
                      >
                        日付
                      </span>
                    </div>
                  </th>

                  <th scope="col" class="px-6 py-3 text-right"></th>
                  <th scope="col" class="px-6 py-3 text-right"></th>
                </tr>
              </thead>
{% for item in object_list%}
              <tbody class="divide-y divide-gray-200 dark:divide-gray-700">
                <tr>
                  <td class="h-px w-72 whitespace-nowrap">
                    <div class="px-6 py-3">
                      <span
                        class="block text-sm font-semibold text-gray-800 dark:text-gray-200"
                        >{{ item.event }}</span
                      >
                    </div>
                  </td>
                  <td class="h-px w-72 whitespace-nowrap">
                    <div class="px-6 py-3">
                      <span
                        class="block text-sm font-semibold text-gray-800 dark:text-gray-200"
                        >{{ item.date }}</span
                      >
                    </div>
                  </td>
                  <td class="h-px w-px whitespace-nowrap">
                    <div class="px-6 py-1.5">
                      <a
                        class="inline-flex items-center gap-x-1.5 text-sm text-blue-600 decoration-2 hover:underline font-medium"
                        href="{% url "logmaneapp:event_update" item.pk %}"
                      >
                        修正
                      </a>
                    </div>
                  </td>
                  <td class="h-px w-px whitespace-nowrap">
                    <div class="px-6 py-1.5">
                      <a
                        class="inline-flex items-center gap-x-1.5 text-sm text-blue-600 decoration-2 hover:underline font-medium"
                        href="{% url "logmaneapp:event_delete" item.pk %}"
                      >
                        削除
                      </a>
                    </div>
                  </td>
                </tr>
{% endfor %}
            <!-- Footer -->
            <div
              class="px-6 py-4 grid gap-3 md:flex md:justify-between md:items-center border-t border-gray-200 dark:border-gray-700"
            >
              {% comment %} <div>
                <p class="text-sm text-gray-600 dark:text-gray-400">
                  <span class="font-semibold text-gray-800 dark:text-gray-200"
                    >6</span
                  >
                  results
                </p>
              </div> {% endcomment %}

              <div>
                <div class="inline-flex gap-x-2">
                  <button
                    type="button"
                    class="py-2 px-3 inline-flex justify-center items-center gap-2 rounded-md border font-medium bg-white text-gray-700 shadow-sm align-middle hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-white focus:ring-blue-600 transition-all text-sm dark:bg-slate-900 dark:hover:bg-slate-800 dark:border-gray-700 dark:text-gray-400 dark:hover:text-white dark:focus:ring-offset-gray-800"
                  >
                    <svg
                      class="w-3 h-3"
                      xmlns="http://www.w3.org/2000/svg"
                      width="16"
                      height="16"
                      fill="currentColor"
                      viewBox="0 0 16 16"
                    >
                      <path
                        fill-rule="evenodd"
                        d="M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z"
                      />
                    </svg>
                    Prev
                  </button>

                  <button
                    type="button"
                    class="py-2 px-3 inline-flex justify-center items-center gap-2 rounded-md border font-medium bg-white text-gray-700 shadow-sm align-middle hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-white focus:ring-blue-600 transition-all text-sm dark:bg-slate-900 dark:hover:bg-slate-800 dark:border-gray-700 dark:text-gray-400 dark:hover:text-white dark:focus:ring-offset-gray-800"
                  >
                    Next
                    <svg
                      class="w-3 h-3"
                      xmlns="http://www.w3.org/2000/svg"
                      width="16"
                      height="16"
                      fill="currentColor"
                      viewBox="0 0 16 16"
                    >
                      <path
                        fill-rule="evenodd"
                        d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z"
                      />
                    </svg>
                  </button>
                </div>
              </div>
            </div>
            <!-- End Footer -->
          </div>
        </div>
      </div>
    </div>
    <!-- End Card -->
  </div>
  <!-- End Table Section -->
{% endblock content %}

logmaneapp/templates/index.html
{% extends 'base.html' %}

{% block title %}ホーム{% endblock title %}

{% block content %}

  <div class="relative overflow-hidden before:absolute before:top-0 before:left-1/2 before:bg-[url('../svg/component/polygon.svg')] before:bg-no-repeat before:bg-top before:bg-cover before:w-full before:h-full before:-z-[1] before:transform before:-translate-x-1/2 dark:before:bg-[url('../svg/component/polygon-dark.svg')]">
  <div class="max-w-[85rem] mx-auto px-4 sm:px-6 lg:px-8 pt-24 pb-10">

    <!-- Buttons -->
    <div class="mt-8 grid gap-3 w-full sm:inline-flex sm:justify-center">
      <a class="inline-flex justify-center items-center gap-x-3 text-center bg-gradient-to-tl from-blue-600 to-violet-600 hover:from-violet-600 hover:to-blue-600 border border-transparent text-white text-sm font-medium rounded-md focus:outline-none focus:ring-2 focus:ring-blue-600 focus:ring-offset-2 focus:ring-offset-white py-3 px-4 dark:focus:ring-offset-gray-800" href="{% url "logmaneapp:athlete_create" %}">
        選手登録
        <svg class="w-3 h-3" width="16" height="16" viewBox="0 0 16 16" fill="none">
          <path d="M5.27921 2L10.9257 7.64645C11.1209 7.84171 11.1209 8.15829 10.9257 8.35355L5.27921 14" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
        </svg>
      </a>
      <a class="w-full sm:w-auto inline-flex justify-center items-center gap-x-3 text-center bg-blue-600 hover:bg-blue-700 border border-transparent text-white font-medium rounded-md focus:outline-none focus:ring-2 focus:ring-blue-600 focus:ring-offset-2 focus:ring-offset-white transition py-3 px-4 dark:focus:ring-offset-gray-800" href="{% url "logmaneapp:event_create" %}">
        大会登録
      </a>
      <a class="relative group inline-flex justify-center items-center gap-x-3.5 text-center bg-white border hover:border-gray-300 shadow-sm font-mono text-sm font-medium rounded-md focus:outline-none focus:ring-2 focus:ring-gray-400 focus:ring-offset-2 focus:ring-offset-white transition p-2 pl-4 dark:bg-slate-900 dark:border-gray-800 dark:hover:border-gray-600 dark:shadow-slate-700/[.7] dark:text-white dark:focus:ring-gray-700 dark:focus:ring-offset-gray-800" href="{% url "logmaneapp:event_records_create" %}">
        大会の記録登録
        <span class="flex justify-center items-center bg-gray-200 rounded-md w-7 h-7 dark:bg-gray-700 dark:text-gray-400">
          <svg class="w-3.5 h-3.5 group-hover:rotate-6 transition" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
            <path d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1h1a1 1 0 0 1 1 1V14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V3.5a1 1 0 0 1 1-1h1v-1z"/>
            <path d="M9.5 1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5h3zm-3-1A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3z"/>
          </svg>
        </span>
      </a>
    </div>
    <!-- End Buttons -->
  </div>
  </div>

{% endblock content %}